# -*- coding: utf-8 -*-
"""DataScienceMasterAssignment25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brGFC3mZyAH8kvHhUaWQYGwTtdqhIEG8

#**Assignment**
## This is the assignment in week 9 ML TOOLBOX - visualization plotly

### Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a scatter plot for age and fare columns in the titanic dataset.
"""

import seaborn as sns
import plotly.graph_objects as go
titanic = sns.load_dataset('titanic')
fig = go.Figure()
fig.add_trace(go.Scatter(x = titanic.age, y = titanic.fare , mode = 'markers'))
fig.show()

"""### Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import plotly.express as px

# Load the tips dataset from Plotly
tips_data = px.data.tips()

# Create a box plot using Plotly express
fig1 = px.box(tips_data, x='day', y='total_bill', title='Box plot of Total Bill by Day')
fig1.show()

"""### Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day" column with the color parameter."""

import plotly.express as px

# Load the tips dataset from Plotly
tips_data = px.data.tips()

# Create a histogram using Plotly express
fig2 = px.histogram(tips_data, x='sex', y='total_bill', color='day', pattern_shape='smoker',
                   title='Histogram of Total Bill by Sex with Smoker Patterns and Day Colors')
fig2.show()

"""### Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for the color parameter.
### Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the dimensions parameter.
"""

import plotly.express as px

# Load the iris dataset from Plotly
iris_data = px.data.iris()

# Create a scatter matrix plot using Plotly express
fig3 = px.scatter_matrix(iris_data, dimensions=['sepal_width', 'sepal_length', 'petal_width', 'petal_length'],
                        color='species', title='Scatter Matrix Plot of Iris Dataset with Species Color')
fig3.show()

"""### Q5. What is Distplot? Using Plotly express, plot a distplot.

In seaborn, the displot function is used to create a flexible and convenient histogram with optional kernel density estimation (KDE) and rug plot. It is a high-level interface for creating distribution plots in seaborn.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Load some example data
data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

# Create a distribution plot using seaborn's displot
sns.displot(data, kde=True, rug=True)

# Show the plot
plt.show()

